# Generated by Django 5.1.1 on 2024-09-29 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodFinder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='distance',
        ),
    ]
