# Generated by Django 5.1.1 on 2024-10-01 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodFinder', '0003_delete_apple_restaurant_address_restaurant_cuisine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='cuisine',
        ),
    ]
