# Generated by Django 5.1.1 on 2024-10-01 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodFinder', '0005_remove_restaurant_address_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
